### ISSUE TITLE
allow disabling common questions

### ISSUE THREAD

**Issue by tunnckoCore** [node-base/base-questions#1]

**Comment by jonschlinkert** [comment]
agreed. it shall be so

**Comment by jonschlinkert** [comment]
I'm just going to remove them from base-questions. and I just realized that their still being loaded in a way that is incompatible with the API changes I made a while ago. lame, I can't believe I missed that

**Comment by tunnckoCore** [comment]
> lame, I can't believe I missed that

hahahahah, yea, sometimes.

**Comment by jonschlinkert** [comment]
resolved by 0.4.0

**Comment by tunnckoCore** [comment]
great!
